FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ng2app

APIs for Angular 2 Practice APP

# Group Doctor List - GET Requests

## Show Doctor List [/api/v1/doctors]

### Show Doctor List [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Data fetched successfully",
            "doctors_list": [
                {   "id": 1,
                    "title": "Doc 1",
                    "gender": "Female",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Allergist",
                    "education": "M.B.B.S.",
                    "profile_pic": "https://dermamedical.co.uk/wp-content/uploads/2015/06/Doctor.jpg"
                },
                
                {   
                    "id": 2,
                    "title": "Doc 2",
                    "gender": "Male",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Dentist",
                    "education": "B.D.S.",
                    "profile_pic": "http://ichef-1.bbci.co.uk/news/660/media/images/76055000/jpg/_76055361_482566485.jpg"
                },
                
                {   
                    "id": 3,
                    "title": "Doc 3",
                    "gender": "Male",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Dermatologist",
                    "education": "B.D.S.",
                    "profile_pic": "http://worldcareintl.wpengine.netdna-cdn.com/wp-content/uploads/2015/11/DoctorMan.png"
                },
                
                {   
                    "id": 4,
                    "title": "Doc 4",
                    "gender": "Male",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Optamologist",
                    "education": "MBBS.",
                    "profile_pic": "http://www.dottorelondon.com/wp-content/uploads/2015/12/doctor1-1.png"
                },
                
                {   
                    "id": 5,
                    "title": "Doc 5",
                    "gender": "Female",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Pedologist",
                    "education": "B.D.S.",
                    "profile_pic": "http://dailyreckoning.com/dr-content/uploads/2013/08/Post_Pic14.jpg"
                },
                
                {   
                    "id": 6,
                    "title": "Doc 6",
                    "gender": "Male",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Nerve specialist",
                    "education": "MBBS",
                    "profile_pic": "http://catalinari.com/wordpress1/wp-content/uploads/2012/11/shutterstock_117021031.jpg"
                }
            ]    
                
        }
        
+ Response 200 (application/json)

        {
            "success": true,
            "message": "Fetched data successfully"
        }

## Show Doctor1 Profile [/api/v1/doctors/1]

Doctor1 Details for Profile

### Show Doctor1 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Doctor details fetched successfully",
            "doctor": 
                {
                    "id": 1,
                    "title": "Doc 1",
                    "gender": "Female",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Allergist",
                    "education": "M.B.B.S.",
                    "profile_pic": "https://dermamedical.co.uk/wp-content/uploads/2015/06/Doctor.jpg"
                }
        }

## Show Doctor2 Profile [/api/v1/doctors/2]

Doctor2 Details for Profile

### Show Doctor2 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Doctor details fetched successfully",
            "doctor": 
                {
                    "id": 2,
                    "title": "Doc 2",
                    "gender": "Male",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Dentist",
                    "education": "B.D.S.",
                    "profile_pic": "http://ichef-1.bbci.co.uk/news/660/media/images/76055000/jpg/_76055361_482566485.jpg"
                }
        }
        
## Show Doctor3 Profile [/api/v1/doctors/3]

Doctor3 Details for Profile

### Show Doctor3 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Doctor details fetched successfully",
            "doctor": 
                {
                    "id": 3,
                    "title": "Doc 3",
                    "gender": "Male",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Dermatologist",
                    "education": "B.D.S.",
                    "profile_pic": "http://worldcareintl.wpengine.netdna-cdn.com/wp-content/uploads/2015/11/DoctorMan.png"
                }
        }
        
## Show Doctor4 Profile [/api/v1/doctors/4]

Doctor4 Details for Profile

### Show Doctor4 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Doctor details fetched successfully",
            "doctor": 
                {
                    "id": 4,
                    "title": "Doc 4",
                    "gender": "Male",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Optamologist",
                    "education": "MBBS.",
                    "profile_pic": "http://www.dottorelondon.com/wp-content/uploads/2015/12/doctor1-1.png"
                }
        }
        
## Show Doctor5 Profile [/api/v1/doctors/5]

Doctor5 Details for Profile

### Show Doctor5 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Doctor details fetched successfully",
            "doctor": 
                {
                    "id": 5,
                    "title": "Doc 5",
                    "gender": "Female",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Pedologist",
                    "education": "B.D.S.",
                    "profile_pic": "http://dailyreckoning.com/dr-content/uploads/2013/08/Post_Pic14.jpg"
                }
        }
        
## Show Doctor6 Profile [/api/v1/doctors/6]

Doctor6 Details for Profile

### Show Doctor6 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Doctor details fetched successfully",
            "doctor": 
                {
                    "id": 6,
                    "title": "Doc 6",
                    "gender": "Male",
                    "bio": "Dental Solutions Is A Dental Clinic Based In Bangalore, India & We Offer High Quality Yet Low Cost Dental Clinic Experience. Your Quest For A Dentist Abroad Is Over! Equipped With State Of The Art Infrastructure, Our Laser Dentist Who Specializes In Laser Teeth Whitening,laser Dentistry,offers Complete Oral And Dental Care.our Team Consists Of Experienced Periodontist,prosthodontist,well Qualified Dental Surgeons,also Dentist From All Other Specialities Like Orthodontist,cosmetic Surgeons Are Available With Us",
                    "speciality": "Nerve specialist",
                    "education": "MBBS",
                    "profile_pic": "http://catalinari.com/wordpress1/wp-content/uploads/2012/11/shutterstock_117021031.jpg"
                }
        }


## Show Doctor1 Patients List [/api/v1/doctors/1/patients_list]

Doctor1 Patients list on Doctor's Dashboard

### Show Doctor1 Patients List [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patients list fetched successfully",
            "patients": 
            [
                {
                    "patient_id":1,
                    "patient_name":"Test1 Case1",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                },
                {
                    "patient_name":"Sample Pat",
                    "patient_id":2,
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                }
            ]
        }

## Show Doctor2 Patients List [/api/v1/doctors/2/patients_list]

Doctor2 Patients list on Doctor's Dashboard

### Show Doctor2 Patients List [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patients list fetched successfully",
            "patients": 
            [
                {
                    "patient_id":1,
                    "patient_name":"Test1 Case1",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                },
                {
                    "patient_name":"Sample Pat",
                    "patient_id":2,
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                }
            ]
        }

## Show Doctor3 Patients List [/api/v1/doctors/3/patients_list]

Doctor3 Patients list on Doctor's Dashboard

### Show Doctor3 Patients List [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patients list fetched successfully",
            "patients": 
            [
                {
                    "patient_id":1,
                    "patient_name":"Test1 Case1",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                },
                {
                    "patient_name":"Sample Pat",
                    "patient_id":2,
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                },
                {
                    "patient_id":3,
                    "patient_name":"Test3 Case3",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.djmag.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fdjmag_landscape%2Fpublic%2Farticle%2Fimage%2Fhardwellmiller.jpg%3Fitok%3D3UG2EwDm&imgrefurl=http%3A%2F%2Fwww.djmag.com%2Fcontent%2Ftop-100-djs-profile-hardwell&docid=P0G5L-RJVzo0HM&tbnid=xiAWdc-2Ey8NzM%3A&w=628&h=338&ved=0ahUKEwj7wKaig4vMAhWEk5QKHZbkA-k4ZBAzCC0oKjAq&iact=mrc&uact=8"
                },
                {
                    "patient_name":"Sample4 Pat4",
                    "patient_id":4,
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fi.dailymail.co.uk%2Fi%2Fpix%2F2011%2F04%2F19%2Farticle-1378432-007ABE9B00000258-142_1024x615_large.jpg&imgrefurl=http%3A%2F%2Fwww.dailymail.co.uk%2Fnews%2Farticle-1378432%2FJack-Ripper-FBI-dossier-reveals-chilling-profile-released-100-years-late.html&docid=HEeN0jHYoqoD5M&tbnid=yhPY1hIJQCFB7M%3A&w=1024&h=615&ved=0ahUKEwj7wKaig4vMAhWEk5QKHZbkA-k4ZBAzCE4oSzBL&iact=mrc&uact=8"
                }
            ]
        }        

## Show Doctor4 Patients List [/api/v1/doctors/4/patients_list]

Doctor4 Patients list on Doctor's Dashboard

### Show Doctor4 Patients List [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patients list fetched successfully",
            "patients": 
            [
                {
                    "patient_id":1,
                    "patient_name":"Test1 Case1",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                },
                {
                    "patient_name":"Sample Pat",
                    "patient_id":2,
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                },
                {
                    "patient_id":3,
                    "patient_name":"Test3 Case3",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.djmag.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fdjmag_landscape%2Fpublic%2Farticle%2Fimage%2Fhardwellmiller.jpg%3Fitok%3D3UG2EwDm&imgrefurl=http%3A%2F%2Fwww.djmag.com%2Fcontent%2Ftop-100-djs-profile-hardwell&docid=P0G5L-RJVzo0HM&tbnid=xiAWdc-2Ey8NzM%3A&w=628&h=338&ved=0ahUKEwj7wKaig4vMAhWEk5QKHZbkA-k4ZBAzCC0oKjAq&iact=mrc&uact=8"
                },
                {
                    "patient_name":"Sample4 Pat4",
                    "patient_id":4,
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fi.dailymail.co.uk%2Fi%2Fpix%2F2011%2F04%2F19%2Farticle-1378432-007ABE9B00000258-142_1024x615_large.jpg&imgrefurl=http%3A%2F%2Fwww.dailymail.co.uk%2Fnews%2Farticle-1378432%2FJack-Ripper-FBI-dossier-reveals-chilling-profile-released-100-years-late.html&docid=HEeN0jHYoqoD5M&tbnid=yhPY1hIJQCFB7M%3A&w=1024&h=615&ved=0ahUKEwj7wKaig4vMAhWEk5QKHZbkA-k4ZBAzCE4oSzBL&iact=mrc&uact=8"
                }
            ]
        }      
        
## Show Doctor5 Patients List [/api/v1/doctors/5/patients_list]

Doctor5 Patients list on Doctor's Dashboard

### Show Doctor5 Patients List [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patients list fetched successfully",
            "patients": 
            [
               {
                    "patient_id":1,
                    "patient_name":"Test1 Case1",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                },
                {
                    "patient_name":"Sample Pat",
                    "patient_id":2,
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                },
                {
                    "patient_id":3,
                    "patient_name":"Test3 Case3",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.djmag.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fdjmag_landscape%2Fpublic%2Farticle%2Fimage%2Fhardwellmiller.jpg%3Fitok%3D3UG2EwDm&imgrefurl=http%3A%2F%2Fwww.djmag.com%2Fcontent%2Ftop-100-djs-profile-hardwell&docid=P0G5L-RJVzo0HM&tbnid=xiAWdc-2Ey8NzM%3A&w=628&h=338&ved=0ahUKEwj7wKaig4vMAhWEk5QKHZbkA-k4ZBAzCC0oKjAq&iact=mrc&uact=8"
                }
            ]
        }  
        
## Show Doctor6 Patients List [/api/v1/doctors/6/patients_list]

Doctor6 Patients list on Doctor's Dashboard

### Show Doctor6 Patients List [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patients list fetched successfully",
            "patients": 
            [
                 {
                    "patient_id":1,
                    "patient_name":"Test1 Case1",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                }
            ]
        }         

## Show Patients1 Profile [/api/v1/patients/1]

Patients1 Profile

### Show Patients1 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patient details fetched successfully",
            "profile": 
                {
                    "status":"Scheduled",
                    "patient_name":"Test1 Case1",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female",
                    "bio": "I need some good dentist who can provide some relief.",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                }
        } 

## Show Patients2 Profile [/api/v1/patients/2]

Patients2 Profile

### Show Patients2 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patient details fetched successfully",
            "profile": 
                {
                    "patient_name":"Sample Pat",
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232",
                    "bio": "I am facing some issues with stomach. Please treat me.",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.kpoplyrics.net%2Fwp-content%2Fuploads%2F2012%2F09%2F100per-minwoo.jpg&imgrefurl=http%3A%2F%2Fwww.kpoplyrics.net%2F100-members-profile.html&docid=jAI-uUx63gshyM&tbnid=Fqo2qjGkkRWBsM%3A&w=420&h=630&ved=0ahUKEwigrI6Bg4vMAhVD0mMKHSTOAXsQMwg9KBcwFw&iact=mrc&uact=8"
                }
        }

## Show Patients3 Profile [/api/v1/patients/3]

Patients3 Profile

### Show Patients3 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patient details fetched successfully",
            "profile": 
                {
                    "patient_name":"Test3 Case3",
                    "patient_email":"patient1@gmail.com",
                    "patient_phone_number":"911231231231",
                    "patient_age":23,
                    "patient_gender":"Female".
                    "bio": "I am facing some issues with stomach. Please treat me.",
                    "profile_pic": "https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.djmag.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Fdjmag_landscape%2Fpublic%2Farticle%2Fimage%2Fhardwellmiller.jpg%3Fitok%3D3UG2EwDm&imgrefurl=http%3A%2F%2Fwww.djmag.com%2Fcontent%2Ftop-100-djs-profile-hardwell&docid=P0G5L-RJVzo0HM&tbnid=xiAWdc-2Ey8NzM%3A&w=628&h=338&ved=0ahUKEwj7wKaig4vMAhWEk5QKHZbkA-k4ZBAzCC0oKjAq&iact=mrc&uact=8"
                }
        } 

## Show Patients4 Profile [/api/v1/patients/4]

Patients4 Profile

### Show Patients4 Profile [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patient details fetched successfully",
            "profile": 
                {
                    "patient_name":"Sample4 Pat4",
                    "patient_age":12,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232"
                    "bio": "I am facing some issues with stomach. Please treat me."
                }
        } 

## Update Patient Profile [/api/v1/patients/5]

Update Patient Profile

### Update Patient Profile [PUT]

+ Response 200 (application/json)

        {
            "success": true,
            "message": "Patient details updated successfully",
            "profile": 
                {
                    "patient_name":"Sample1",
                    "patient_age":98,
                    "patient_gender":"Male",
                    "patient_email":"asda@dasdas.com",
                    "patient_phone_number": "92342424232"
                    "bio": "I am facing some issues with stomach. Please treat me."
                }
        }